### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised

### ISSUE THREAD

**Issue by roysbike** [roldaojr/zabbix_lldp_map#1]
My zabbix server working https 
```

/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "zabbix_lldp_map.py", line 224, in <module>
    get_config('zabbix.password'))
  File "zabbix_lldp_map.py", line 46, in __init__
    self.api.login(username, password)
  File "/usr/local/lib/python3.5/dist-packages/pyzabbix/__init__.py", line 72, in login
    self.auth = self.user.login(user=user, password=password)
  File "/usr/local/lib/python3.5/dist-packages/pyzabbix/__init__.py", line 166, in fn
    args or kwargs
  File "/usr/local/lib/python3.5/dist-packages/pyzabbix/__init__.py", line 143, in do_request
    raise ZabbixAPIException(msg, response_json['error']['code'])
pyzabbix.ZabbixAPIException: ('Error -32602: Invalid params., No permissions for system access.', -32602)

```

**Comment by roysbike** [comment]
sorry. Its ok
