### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get' 

### ISSUE THREAD

**Issue by roysbike** [roldaojr/zabbix_lldp_map#2]
```
zabbix:
  url: https://host
  username: user
  password: password
  hostgroup: group_switch
  map:
    name: Network Map
    width: 1275
    height: 690
    default_icon: Switch_(24)
  inventory_fields:
    - model

```

```
Connecting to zabbix
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Getting zabbix hosts from group group_switch
Traceback (most recent call last):
  File "zabbix_lldp_map.py", line 224, in <module>
    devices = get_devices_from_zabbix(zabbix, get_config('zabbix.hostgroup'))
  File "zabbix_lldp_map.py", line 87, in get_devices_from_zabbix
    sysname=host['inventory'].get('name', '')
AttributeError: 'list' object has no attribute 'get'

```

**Comment by roysbike** [comment]
I filled out an inventory, but now another error

```
Connecting to zabbix
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Getting zabbix hosts from group group_switch
Getting data from hosts
Getting data from hosts
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 136, in call_graphviz
    **kwargs
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zabbix_lldp_map.py", line 230, in <module>
    graph.write_png(get_config('graphviz.imagefile'))
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1734, in new_method
    encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.

```

**Comment by roysbike** [comment]
> I filled out an inventory, but now another error
> 
> ```
> Connecting to zabbix
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> Getting zabbix hosts from group group_switch
> Getting data from hosts
> Getting data from hosts
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1915, in create
>     working_dir=tmp_dir,
>   File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 136, in call_graphviz
>     **kwargs
>   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> FileNotFoundError: [Errno 2] No such file or directory: 'dot'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "zabbix_lldp_map.py", line 230, in <module>
>     graph.write_png(get_config('graphviz.imagefile'))
>   File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1734, in new_method
>     encoding=encoding)
>   File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1817, in write
>     s = self.create(prog, format, encoding=encoding)
>   File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1922, in create
>     raise OSError(*args)
> FileNotFoundError: [Errno 2] "dot" not found in path.
> ```

I install on debian 9 python3-pydot, but another error


```
Connecting to zabbix
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Getting zabbix hosts from group group_switch
Getting data from hosts
Getting data from hosts
"dot" with args ['-Tpng', '/tmp/tmp3xrre476'] returned code: 1

stdout, stderr:
 b''
b"Error: /tmp/tmp3xrre476: syntax error in line 5 near ','\n"

Traceback (most recent call last):
  File "zabbix_lldp_map.py", line 230, in <module>
    graph.write_png(get_config('graphviz.imagefile'))
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1734, in new_method
    encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/pydot.py", line 1945, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1

```

**Comment by roysbike** [comment]
New error 

```
Updaing map Network Map (6)...
Updaing map {'selements': [{'elementtype': 0, 'elements': [{'hostid': '10484'}], 'x': 126, 'selementid': 3, 'iconid_off': 'Switch_(24)', 'y': 18, 'use_iconmap': 1}, {'elementtype': 0, 'elements': [{'hostid': '10482'}], 'x': 18, 'selementid': 1, 'iconid_off': 'Switch_(24)', 'y': 18, 'use_iconmap': 1}, {'elementtype': 0, 'elements': [{'hostid': '10483'}], 'x': 72, 'selementid': 2, 'iconid_off': 'Switch_(24)', 'y': 18, 'use_iconmap': 1}], 'label_type_image': 0, 'links': [], 'width': 1275, 'name': 'Network Map', 'label_format': 1, 'height': 690}
Traceback (most recent call last):
  File "./zabbix_lldp_map.py", line 236, in <module>
    generate_zabbix_map(zabbix, graph, map_cfg['name'], map_cfg['width'], map_cfg['height'])
  File "./zabbix_lldp_map.py", line 216, in generate_zabbix_map
    zabbix.api.map.update(map_params)
  File "/usr/local/lib/python3.5/dist-packages/pyzabbix/__init__.py", line 166, in fn
    args or kwargs
  File "/usr/local/lib/python3.5/dist-packages/pyzabbix/__init__.py", line 143, in do_request
    raise ZabbixAPIException(msg, response_json['error']['code'])
pyzabbix.ZabbixAPIException: ('Error -32602: Invalid params., No icon for map element "".', -32602)

```
