### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Alx7528** [roldaojr/zabbix_lldp_map#4]
Hello! Thank you for this software!

Help me please!

root@monitor:/etc/zabbix/zabbix_lldp_map# python3.6 zabbix_lldp_map.py
Connecting to zabbix
Getting zabbix hosts from group CITYNET
Traceback (most recent call last):
  File "zabbix_lldp_map.py", line 226, in <module>
    devices = get_devices_from_zabbix(zabbix, get_config('zabbix.hostgroup'))
  File "zabbix_lldp_map.py", line 84, in get_devices_from_zabbix
    host['inventory']['ip_address'] = host['interfaces'][-1]['ip']
TypeError: list indices must be integers or slices, not str
root@monitor:/etc/zabbix/zabbix_lldp_map#

**Comment by Alx7528** [comment]
Work fine with correct python3.6 version.
