### ISSUE TITLE
Zabbix 5.0 Api Support?

### ISSUE THREAD

**Issue by roysbike** [roldaojr/zabbix_lldp_map#5]
```
Getting zabbix hosts from group test
Traceback (most recent call last):
  File "zabbix_lldp_map.py", line 226, in <module>
    devices = get_devices_from_zabbix(zabbix, get_config('zabbix.hostgroup'))
  File "zabbix_lldp_map.py", line 82, in get_devices_from_zabbix
    hosts = self.get_hosts_from_group(hostgroup)
  File "zabbix_lldp_map.py", line 53, in get_hosts_from_group
    'groupids': groups[0]['groupid'],
IndexError: list index out of range

```

**Comment by roysbike** [comment]
Sorry. Is work

**Comment by roysbike** [comment]
Sorry. Is work

**Comment by roysbike** [comment]
Sorry. Is work
